import Head from "next/head";

export default function Central() {
  return (
    <>
      <Head>
        <title>Central Hub | The Planet Hub</title>
      </Head>

      <section className="min-h-screen bg-gradient-to-b from-black to-gray-900 text-white px-6 py-20">
        <h1 className="text-4xl md:text-5xl font-bold mb-6 text-center">
          🌍 Central Hub
        </h1>
        <p className="text-lg text-center max-w-3xl mx-auto mb-12">
          Your mission control for planetary research. Discover challenges, track progress, and shape the future of Earth.
        </p>

        {/* Trending Missions */}
        <div className="mb-16">
          <h2 className="text-2xl font-semibold mb-4">🔥 Trending Missions</h2>
          <div className="grid md:grid-cols-2 gap-6">
            {[
              "Decentralized Ocean Cleanup Mesh",
              "Zero-Waste AI Smart Cities",
              "Terraforming Sustainable Deserts",
              "SolarGrid: Scalable Solar for Villages"
            ].map((mission, i) => (
              <div key={i} className="bg-gray-800 p-5 rounded-xl shadow hover:bg-gray-700 transition">
                <h3 className="text-lg font-semibold">{mission}</h3>
                <p className="text-sm mt-2 text-gray-300">
                  AI-curated mission with community votes & research opportunities.
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Top Researchers */}
        <div className="mb-16">
          <h2 className="text-2xl font-semibold mb-4">🏆 Top Planetary Engineers</h2>
          <ul className="space-y-3">
            {["Aryan Patel", "Zara Mehta", "Ayaan Khan", "Dr. Nisha Verma"].map((name, i) => (
              <li key={i} className="bg-gray-800 p-4 rounded-xl flex justify-between items-center">
                <span>{name}</span>
                <span className="text-sm text-green-400">Impact Score: {900 - i * 30}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* AI-Generated Idea */}
        <div className="mb-16">
          <h2 className="text-2xl font-semibold mb-4">🤖 Weekly AI Theory</h2>
          <div className="bg-gray-800 p-6 rounded-xl">
            <p className="text-gray-200 italic">
              “What if we created a fungus-based biodegradable polymer that eats microplastics from groundwater pipelines without harming the soil microbiome?”
            </p>
            <p className="mt-4 text-sm text-gray-400">— Generated by PlanetAI Model v1.0</p>
          </div>
        </div>

        {/* CTA to Launch Pad */}
        <div className="text-center mt-20">
          <a href="/launchpad" className="inline-block bg-green-500 hover:bg-green-600 text-black font-bold py-3 px-6 rounded-full transition">
            🚀 Launch Your Own Mission
          </a>
        </div>
      </section>
    </>
  );
}
